- name: Install mysql
  hosts: mysql
  become: yes
  
  tasks:
  - name: Install mysql server on mysql server
    ansible.builtin.package:
       name: mysql
       state: installed

- name: Start service mysql, if not started
  ansible.builtin.service:
    name: mysqld
    state: started


 