- name: create ec2 and R53 records
  connection: local
  hosts: local
  vars:
      subnet_id: subnet-079a782bd29650977
      sg_id: sg-01c4082245f76e04f
      ami_id: ami-09c813fb71547fc4f
      instance_type: t3.micro
      instances:
        - mysql1
        - backend1
        - frontend1
  tasks:
    - name: create ec2_instances
      amazon.aws.ec2_instances:
        name: "{{ mysql1 }}"
        subnet_id: "{{ subnet_id }}"
        security_group: "{{ sg_id }}"
        image_id: "{{ ami_id }}"
        instance_type: "{{ instance_type }}"
      loop: "{{ instances }}"
        w